FROM php-fpm:latest

COPY ./ /var/www/ternobo
COPY ./nginx.conf ./etc/nginx/sites-available


RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

RUN export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")" [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

RUN cd /var/www/ternobo 
RUN composer install
RUN npm install
