<?php
return [
    'settings' => "Settings and Privacy",

    'account' => "Account",
    'about-ternobo' => "About Ternobo",

    'cookies' => "Cookies",

    'login-and-security' => "Login and Security",
    'information-security' => "Information and Account Accesses",

    'change-username' => "Change Username",
    'our-suggestion' => "Our Suggestions",

    'phone-number' => "Phone Number",
    'change-phone-number' => "Change Phone Number",
    'phone-number-ph' => "09123456789",
    'wrong-phone-q' => "Wrong phonenumber?",

    'change-password' => "Change Password",
    'current-password' => "Current Password",
    'confirm-password' => "Confirm Password",

    "change-username" => "Change Username",
    "our-suggestions" => "Our Suggestions",

    'current-session' => "Current Session",
    'active-session' => "Active Sessions",

    'deactive-device-des-1' => 'Disabling your account will make your content and page inaccessible to other users.',
    'deactive-device-des-2' => 'If your account is inactive for more than <strong class="text-danger">2 years</strong>, all your information <span class="text-grey">(content, profile information and your personal page)</span> will be irrevocably deleted.',
    'deactive-device-des-3' => 'Your account will be deactivated until you log back in.',

    'two-step-verification' => "Two-step Verification",
    'ts-des-1' => "Two-step verification protects your account by requiring an additional code when you log in on a device we don't recognize.",
    'ts-title-2' => "Security Method",
    'ts-des-2' => "Choose how you want us to send security codes.",
    'method-app' => "Authentication App",
    'method-sms' => "Text Message",
    'ts-title-3' => "Set Up Two-Step Verification",
    'ts-des-3' => "If you have multiple authentication apps, or have one on another device, you can scan the QR code above in the authentication app you want to use.",
    'ts-des-4' => "If your app asks for an account name, you can use Ternobo.",
    'ts-des-5' => "Once your authentication app generates its own 6-digit code, come back to Ternobo and enter it.",
    'confirmation-code' => "Confirmation Code",
    'ts-des-6' => "Enter the 6-digit code generated by Duo mobile.",
    'ts-title-5' => "Two-Step Authentication Is On",
    'ts-des-7' => "We'll ask you for a code in addition to your password when you log in on a device we don't recognize.",
    'ts-des-8' => "Enter the 6-digit code we sent to your phone to finish setting up two-step verification.",
    'ts-des-9' => "We'll text a code to this number any time you try to log in on a device we don't recognize.",
    'click-copy' => "Click to copy",
    'ts-des-10' => "If you lose your phone or can't receive a code via text message or an authentication app, you can use these codes to get back into your account. Save them in a safe place.",
    'ts-des-11' => "Each code can only be used once. You can also get new codes if you're worried this set has been stolen, or if you've already used most of them.",
    "click-to-copy" => "Click to Copy",
    "resend" => "Resend",

    'deactivate-account' => "Deactivate Account",
    'website-lang' => "Language",
];
