export default [
    { "fips": "AJ", "iso": "AZ", "domain": ".az", "en_name": "Azerbaijan", "fa_name": "آذربایجان" },
    { "fips": "AA", "iso": "AW", "domain": ".aw", "en_name": "Aruba", "fa_name": "آروبا" },
    { "fips": "AR", "iso": "AR", "domain": ".ar", "en_name": "Argentina", "fa_name": "آرژانتین" },
    { "fips": "SF", "iso": "ZA", "domain": ".za", "en_name": "South Africa", "fa_name": "آفریقای جنوبی" },
    { "fips": "AL", "iso": "AL", "domain": ".al", "en_name": "Albania", "fa_name": "آلبانی" },
    { "fips": "GM", "iso": "DE", "domain": ".de", "en_name": "Germany", "fa_name": "آلمان" },
    { "fips": "NT", "iso": "AN", "domain": ".an", "en_name": "Netherlands Antilles", "fa_name": "آنتیل هلند" },
    { "fips": "AC", "iso": "AG", "domain": ".ag", "en_name": "Antigua and Barbuda", "fa_name": "آنتیگوا و باربودا" },
    { "fips": "AN", "iso": "AD", "domain": ".ad", "en_name": "Andorra", "fa_name": "آندورا" },
    { "fips": "AO", "iso": "AO", "domain": ".ao", "en_name": "Angola", "fa_name": "آنگولا" },
    { "fips": "AV", "iso": "AI", "domain": ".ai", "en_name": "Anguilla", "fa_name": "آنگویلا" },
    { "fips": "AU", "iso": "AT", "domain": ".at", "en_name": "Austria", "fa_name": "اتریش" },
    { "fips": "ET", "iso": "ET", "domain": ".et", "en_name": "Ethiopia", "fa_name": "اتیوپی" },
    { "fips": "JO", "iso": "JO", "domain": ".jo", "en_name": "Jordan", "fa_name": "اردن" },
    { "fips": "AM", "iso": "AM", "domain": ".am", "en_name": "Armenia", "fa_name": "ارمنستان" },
    { "fips": "UY", "iso": "UY", "domain": ".uy", "en_name": "Uruguay", "fa_name": "اروگوئه" },
    { "fips": "ER", "iso": "ER", "domain": ".er", "en_name": "Eritrea", "fa_name": "اریتره" },
    { "fips": "UZ", "iso": "UZ", "domain": ".uz", "en_name": "Uzbekistan", "fa_name": "ازبکستان" },
    { "fips": "SV", "iso": "SJ", "domain": ".sj", "en_name": "Svalbard", "fa_name": "سوالبار" },
    { "fips": "AS", "iso": "AU", "domain": ".au", "en_name": "Australia", "fa_name": "استرالیا" },
    { "fips": "EN", "iso": "EE", "domain": ".ee", "en_name": "Estonia", "fa_name": "استونی" },
    { "fips": "IS", "iso": "IL", "domain": ".il", "en_name": "Palestine (Occupied Land)", "fa_name": "فلسطین (سرزمین اشغالی)" },
    { "fips": "LO", "iso": "SK", "domain": ".sk", "en_name": "Slovakia", "fa_name": "اسلواکی" },
    { "fips": "SI", "iso": "SI", "domain": ".si", "en_name": "Slovenia", "fa_name": "اسلوونی" },
    { "fips": "SP", "iso": "ES", "domain": ".es", "en_name": "Spain", "fa_name": "اسپانیا" },
    { "fips": "AT", "iso": "-", "domain": "-", "en_name": "Ashmore and Cartier Islands", "fa_name": "اشکمور و جزایر کارتیه" },
    { "fips": "AF", "iso": "AF", "domain": ".af", "en_name": "Afghanistan", "fa_name": "افغانستان" },
    { "fips": "AG", "iso": "DZ", "domain": ".dz", "en_name": "Algeria", "fa_name": "الجزایر" },
    { "fips": "ES", "iso": "SV", "domain": ".sv", "en_name": "El Salvador", "fa_name": "السالوادور" },
    { "fips": "AE", "iso": "AE", "domain": ".ae", "en_name": "United Arab Emirates", "fa_name": "امارات متحده عربی" },
    { "fips": "ID", "iso": "ID", "domain": ".id", "en_name": "Indonesia", "fa_name": "اندونزی" },
    { "fips": "UK", "iso": "GB", "domain": ".uk", "en_name": "United Kingdom", "fa_name": "انگلستان" },
    { "fips": "UP", "iso": "UA", "domain": ".ua", "en_name": "Ukraine", "fa_name": "اوکراین" },
    { "fips": "UG", "iso": "UG", "domain": ".ug", "en_name": "Uganda", "fa_name": "اوگاندا" },
    { "fips": "EC", "iso": "EC", "domain": ".ec", "en_name": "Ecuador", "fa_name": "اکوادور" },
    { "fips": "US", "iso": "US", "domain": ".us", "en_name": "United States", "fa_name": "ایالات متحده" },
    { "fips": "IT", "iso": "IT", "domain": ".it", "en_name": "Italy", "fa_name": "ایتالیا" },
    { "fips": "IR", "iso": "IR", "domain": ".ir", "en_name": "Iran", "fa_name": "ایران" },
    { "fips": "EI", "iso": "IE", "domain": ".ie", "en_name": "Ireland", "fa_name": "ایرلند" },
    { "fips": "IC", "iso": "IS", "domain": ".is", "en_name": "Iceland", "fa_name": "ایسلند" },
    { "fips": "BB", "iso": "BB", "domain": ".bb", "en_name": "Barbados", "fa_name": "باربادوس" },
    { "fips": "BS", "iso": "-", "domain": "-", "en_name": "Bassas da India", "fa_name": "باساس دا هند" },
    { "fips": "WE", "iso": "-", "domain": "-", "en_name": "West Bank", "fa_name": "بانک غرب" },
    { "fips": "BF", "iso": "BS", "domain": ".bs", "en_name": "Bahamas, The", "fa_name": "باهاما" },
    { "fips": "BA", "iso": "BH", "domain": ".bh", "en_name": "Bahrain", "fa_name": "بحرین" },
    { "fips": "BR", "iso": "BR", "domain": ".br", "en_name": "Brazil", "fa_name": "برزیل" },
    { "fips": "BD", "iso": "BM", "domain": ".bm", "en_name": "Bermuda", "fa_name": "برمودا" },
    { "fips": "BX", "iso": "BN", "domain": ".bn", "en_name": "Brunei", "fa_name": "برونئی" },
    { "fips": "BO", "iso": "BY", "domain": ".by", "en_name": "Belarus", "fa_name": "بلاروس" },
    { "fips": "BU", "iso": "BG", "domain": ".bg", "en_name": "Bulgaria", "fa_name": "بلغارستان" },
    { "fips": "BE", "iso": "BE", "domain": ".be", "en_name": "Belgium", "fa_name": "بلژیک" },
    { "fips": "BH", "iso": "BZ", "domain": ".bz", "en_name": "Belize", "fa_name": "بلیز" },
    { "fips": "BG", "iso": "BD", "domain": ".bd", "en_name": "Bangladesh", "fa_name": "بنگلادش" },
    { "fips": "BN", "iso": "BJ", "domain": ".bj", "en_name": "Benin", "fa_name": "بنین" },
    { "fips": "BT", "iso": "BT", "domain": ".bt", "en_name": "Bhutan", "fa_name": "بوتان" },
    { "fips": "BC", "iso": "BW", "domain": ".bw", "en_name": "Botswana", "fa_name": "بوتسوانا" },
    { "fips": "BY", "iso": "BI", "domain": ".bi", "en_name": "Burundi", "fa_name": "بوروندی" },
    { "fips": "UV", "iso": "BF", "domain": ".bf", "en_name": "Burkina Faso", "fa_name": "بورکینافاسو" },
    { "fips": "BK", "iso": "BA", "domain": ".ba", "en_name": "Bosnia and Herzegovina", "fa_name": "بوسنی و هرزگوین" },
    { "fips": "BL", "iso": "BO", "domain": ".bo", "en_name": "Bolivia", "fa_name": "بولیوی" },
    { "fips": "TU", "iso": "TR", "domain": ".tr", "en_name": "Turkey", "fa_name": "ترکیه" },
    { "fips": "TI", "iso": "TJ", "domain": ".tj", "en_name": "Tajikistan", "fa_name": "تاجیکستان" },
    { "fips": "TZ", "iso": "TZ", "domain": ".tz", "en_name": "Tanzania, United Republic of", "fa_name": "تانزانیا، جمهوری متحده" },
    { "fips": "TH", "iso": "TH", "domain": ".th", "en_name": "Thailand", "fa_name": "تایلند" },
    { "fips": "TW", "iso": "TW", "domain": ".tw", "en_name": "Taiwan", "fa_name": "تایوان" },
    { "fips": "RE", "iso": "RE", "domain": ".re", "en_name": "Reunion", "fa_name": "رئونیون" },
    { "fips": "TX", "iso": "TM", "domain": ".tm", "en_name": "Turkmenistan", "fa_name": "ترکمنستان" },
    { "fips": "TD", "iso": "TT", "domain": ".tt", "en_name": "Trinidad and Tobago", "fa_name": "ترینیداد و توباگو" },
    { "fips": "TS", "iso": "TN", "domain": ".tn", "en_name": "Tunisia", "fa_name": "تونس" },
    { "fips": "TN", "iso": "TO", "domain": ".to", "en_name": "Tonga", "fa_name": "تونگا" },
    { "fips": "TV", "iso": "TV", "domain": ".tv", "en_name": "Tuvalu", "fa_name": "توووالو" },
    { "fips": "TL", "iso": "TK", "domain": ".tk", "en_name": "Tokelau", "fa_name": "توکلو" },
    { "fips": "TT", "iso": "TL", "domain": ".tl", "en_name": "East Timor", "fa_name": "تیمور شرقی" },
    { "fips": "JM", "iso": "JM", "domain": ".jm", "en_name": "Jamaica", "fa_name": "جامائیکا" },
    { "fips": "JQ", "iso": "UM", "domain": "-", "en_name": "Johnston Atoll", "fa_name": "جانستون اتول" },
    { "fips": "GI", "iso": "GI", "domain": ".gi", "en_name": "Gibraltar", "fa_name": "جبل الطارق" },
    { "fips": "JE", "iso": "JE", "domain": ".je", "en_name": "Jersey", "fa_name": "جرسی" },
    { "fips": "PG", "iso": "-", "domain": "-", "en_name": "Spratly Islands", "fa_name": "جزایر اسپارتلی" },
    { "fips": "AX", "iso": "AX", "domain": ".ax", "en_name": "Åland Islands", "fa_name": "جزایر الند" },
    { "fips": "TK", "iso": "TC", "domain": ".tc", "en_name": "Turks and Caicos Islands", "fa_name": "جزایر ترکس و کایکوس" },
    { "fips": "CR", "iso": "-", "domain": "-", "en_name": "Coral Sea Islands", "fa_name": "جزایر دریای مرجانی" },
    { "fips": "BP", "iso": "SB", "domain": ".sb", "en_name": "Solomon Islands", "fa_name": "جزایر سلیمان" },
    { "fips": "FO", "iso": "FO", "domain": ".fo", "en_name": "Faroe Islands", "fa_name": "جزایر فارو" },
    { "fips": "FK", "iso": "FK", "domain": ".fk", "en_name": "Falkland Islands (Islas Malvinas)", "fa_name": "جزایر فالکلند (جزایر مالویناس)" },
    { "fips": "RM", "iso": "MH", "domain": ".mh", "en_name": "Marshall Islands", "fa_name": "جزایر مارشال" },
    { "fips": "CQ", "iso": "MP", "domain": ".mp", "en_name": "Northern Mariana Islands", "fa_name": "جزایر ماریانای شمالی" },
    { "fips": "MQ", "iso": "UM", "domain": "-", "en_name": "Midway Islands", "fa_name": "جزایر میدوی" },
    { "fips": "HM", "iso": "HM", "domain": ".hm", "en_name": "Heard Island and McDonald Islands", "fa_name": "جزایر هرد و جزایر مک دونالد" },
    { "fips": "VQ", "iso": "VI", "domain": ".vi", "en_name": "Virgin Islands (US)", "fa_name": "جزایر ویرجین (ایالات متحده)" },
    { "fips": "VI", "iso": "VG", "domain": ".vg", "en_name": "British Virgin Islands", "fa_name": "جزایر ویرجین بریتانیا" },
    { "fips": "PF", "iso": "-", "domain": "-", "en_name": "Paracel Islands", "fa_name": "جزایر پاراسل" },
    { "fips": "PC", "iso": "PN", "domain": ".pn", "en_name": "Pitcairn Islands", "fa_name": "جزایر پیتکرن" },
    { "fips": "CW", "iso": "CK", "domain": ".ck", "en_name": "Cook Islands", "fa_name": "جزایر کوک" },
    { "fips": "CK", "iso": "CC", "domain": ".cc", "en_name": "Cocos (Keeling) Islands", "fa_name": "جزایر کوکوس (کایلینگ)" },
    { "fips": "CJ", "iso": "KY", "domain": ".ky", "en_name": "Cayman Islands", "fa_name": "جزایر کیمن" },
    { "fips": "GO", "iso": "-", "domain": "-", "en_name": "Glorioso Islands", "fa_name": "جزایر گلوریوزو" },
    { "fips": "BV", "iso": "BV", "domain": ".bv", "en_name": "Bouvet Island", "fa_name": "جزیره بووه" },
    { "fips": "IP", "iso": "-", "domain": "-", "en_name": "Clipperton Island", "fa_name": "جزیره کلیپرتون" },
    { "fips": "HQ", "iso": "UM", "domain": "-", "en_name": "Howland Island", "fa_name": "جزیره هاولند" },
    { "fips": "EU", "iso": "-", "domain": "-", "en_name": "Europa Island", "fa_name": "جزیره اروپا" },
    { "fips": "FQ", "iso": "UM", "domain": "-", "en_name": "Baker Island", "fa_name": "جزیره بیکر" },
    { "fips": "TE", "iso": "-", "domain": "-", "en_name": "Tromelin Island", "fa_name": "جزیره ترولین" },
    { "fips": "DQ", "iso": "UM", "domain": "-", "en_name": "Jarvis Island", "fa_name": "جزیره جارویس" },
    { "fips": "JU", "iso": "-", "domain": "-", "en_name": "Juan de Nova Island", "fa_name": "جزیره خوان جزیره نوا" },
    { "fips": "IM", "iso": "IM", "domain": ".im", "en_name": "Isle of Man", "fa_name": "جزیره من" },
    { "fips": "BQ", "iso": "-", "domain": "-", "en_name": "Navassa Island", "fa_name": "جزیره ناواسا" },
    { "fips": "NF", "iso": "NF", "domain": ".nf", "en_name": "Norfolk Island", "fa_name": "جزیره نورفولک" },
    { "fips": "WQ", "iso": "UM", "domain": "-", "en_name": "Wake Island", "fa_name": "جزیره ویک" },
    { "fips": "KT", "iso": "CX", "domain": ".cx", "en_name": "Christmas Island", "fa_name": "جزیره کریسمس" },
    { "fips": "CT", "iso": "CF", "domain": ".cf", "en_name": "Central African Republic", "fa_name": "جمهوری آفریقای مرکزی" },
    { "fips": "DR", "iso": "DO", "domain": ".do", "en_name": "Dominican Republic", "fa_name": "جمهوری دومینیکن" },
    { "fips": "SY", "iso": "SY", "domain": ".sy", "en_name": "Syrian Arab Republic", "fa_name": "جمهوری عربی سوریه" },
    { "fips": "MK", "iso": "MK", "domain": ".mk", "en_name": " Republic of Yugoslav", "fa_name": "جمهوری یوگسلاوی" },
    { "fips": "EZ", "iso": "CZ", "domain": ".cz", "en_name": "Czech Republic", "fa_name": "جمهوری چک" },
    { "fips": "SX", "iso": "GS", "domain": ".gs", "en_name": "South Georgia and the Islands", "fa_name": "جنوب گرجستان و جزایر" },
    { "fips": "GG", "iso": "GE", "domain": ".ge", "en_name": "Georgia", "fa_name": "جورجیا" },
    { "fips": "DJ", "iso": "DJ", "domain": ".dj", "en_name": "Djibouti", "fa_name": "جیبوتی" },
    { "fips": "DA", "iso": "DK", "domain": ".dk", "en_name": "Denmark", "fa_name": "دانمارک" },
    { "fips": "DO", "iso": "DM", "domain": ".dm", "en_name": "Dominica", "fa_name": "دومینیکا" },
    { "fips": "TO", "iso": "TG", "domain": ".tg", "en_name": "Togo", "fa_name": "توگو" },
    { "fips": "RW", "iso": "RW", "domain": ".rw", "en_name": "Rwanda", "fa_name": "رواندا" },
    { "fips": "RS", "iso": "RU", "domain": ".ru", "en_name": "Russia", "fa_name": "روسیه" },
    { "fips": "RO", "iso": "RO", "domain": ".ro", "en_name": "Romania", "fa_name": "رومانی" },
    { "fips": "ZA", "iso": "ZM", "domain": ".zm", "en_name": "Zambia", "fa_name": "زامبیا" },
    { "fips": "FS", "iso": "TF", "domain": ".tf", "en_name": "French Southern and Antarctic Lands", "fa_name": "زمینهای جنوب و جنوب قطب جنوب فرانسه" },
    { "fips": "ZI", "iso": "ZW", "domain": ".zw", "en_name": "Zimbabwe", "fa_name": "زیمبابوه" },
    { "fips": "TP", "iso": "ST", "domain": ".st", "en_name": "Sao Tome and Principe", "fa_name": "سائوتومه و پرنسیپه" },
    { "fips": "IV", "iso": "CI", "domain": ".ci", "en_name": "Cote d'Ivoire", "fa_name": "ساحل عاج" },
    { "fips": "WS", "iso": "WS", "domain": ".ws", "en_name": "Samoa", "fa_name": "ساموآ" },
    { "fips": "AQ", "iso": "AS", "domain": ".as", "en_name": "American Samoa", "fa_name": "ساموای آمریکایی" },
    { "fips": "SM", "iso": "SM", "domain": ".sm", "en_name": "San Marino", "fa_name": "سان مارینو" },
    { "fips": "CE", "iso": "LK", "domain": ".lk", "en_name": "Sri Lanka", "fa_name": "سری لانکا" },
    { "fips": "ST", "iso": "LC", "domain": ".lc", "en_name": "Saint Lucia", "fa_name": "سنت لوسیا" },
    { "fips": "RN", "iso": "MF", "domain": "-", "en_name": "Saint Martin", "fa_name": "سنت مارتین" },
    { "fips": "SH", "iso": "SH", "domain": ".sh", "en_name": "Saint Helena", "fa_name": "سنت هلن" },
    { "fips": "VC", "iso": "VC", "domain": ".vc", "en_name": "Saint Vincent and the Grenadines", "fa_name": "سنت وینسنت و گرنادین" },
    { "fips": "SB", "iso": "PM", "domain": ".pm", "en_name": "Saint Pierre and Miquelon", "fa_name": "سنت پیر و میکلون" },
    { "fips": "SC", "iso": "KN", "domain": ".kn", "en_name": "Saint Kitts and Nevis", "fa_name": "سنت کیتس و نویس" },
    { "fips": "SG", "iso": "SN", "domain": ".sn", "en_name": "Senegal", "fa_name": "سنگال" },
    { "fips": "SN", "iso": "SG", "domain": ".sg", "en_name": "Singapore", "fa_name": "سنگاپور" },
    { "fips": "SW", "iso": "SE", "domain": ".se", "en_name": "Sweden", "fa_name": "سوئد" },
    { "fips": "SZ", "iso": "CH", "domain": ".ch", "en_name": "Switzerland", "fa_name": "سوئیس" },
    { "fips": "WZ", "iso": "SZ", "domain": ".sz", "en_name": "Swaziland", "fa_name": "اسواتینی" },
    { "fips": "SU", "iso": "SD", "domain": ".sd", "en_name": "Sudan", "fa_name": "سودان" },
    { "fips": "NS", "iso": "SR", "domain": ".sr", "en_name": "Suriname", "fa_name": "سورینام" },
    { "fips": "SO", "iso": "SO", "domain": ".so", "en_name": "Somalia", "fa_name": "سومالی" },
    { "fips": "SL", "iso": "SL", "domain": ".sl", "en_name": "Sierra Leone", "fa_name": "سیرا لئون" },
    { "fips": "SE", "iso": "SC", "domain": ".sc", "en_name": "Seychelles", "fa_name": "سیشل" },
    { "fips": "CI", "iso": "CL", "domain": ".cl", "en_name": "Chile", "fa_name": "شیلی" },
    { "fips": "WI", "iso": "EH", "domain": ".eh", "en_name": "Western Sahara", "fa_name": "صحرای غربی" },
    { "fips": "RI", "iso": "RS", "domain": ".rs", "en_name": "Serbia", "fa_name": "صربستان" },
    { "fips": "YI", "iso": "CS", "domain": ".yu", "en_name": "Serbia and Montenegro", "fa_name": "صربستان و مونته‌نگرو" },
    { "fips": "IZ", "iso": "IQ", "domain": ".iq", "en_name": "Iraq", "fa_name": "عراق" },
    { "fips": "LY", "iso": "LY", "domain": ".ly", "en_name": "Libyan Arab", "fa_name": "لیبی" },
    { "fips": "SA", "iso": "SA", "domain": ".sa", "en_name": "Saudi Arabia", "fa_name": "عربستان سعودی" },
    { "fips": "MU", "iso": "OM", "domain": ".om", "en_name": "Oman", "fa_name": "عمان" },
    { "fips": "GH", "iso": "GH", "domain": ".gh", "en_name": "Ghana", "fa_name": "غنا" },
    { "fips": "FR", "iso": "FR", "domain": ".fr", "en_name": "France", "fa_name": "فرانسه" },
    { "fips": "FI", "iso": "FI", "domain": ".fi", "en_name": "Finland", "fa_name": "فنلاند" },
    { "fips": "FJ", "iso": "FJ", "domain": ".fj", "en_name": "Fiji", "fa_name": "فیجی" },
    { "fips": "RP", "iso": "PH", "domain": ".ph", "en_name": "Philippines", "fa_name": "فیلیپین" },
    { "fips": "CY", "iso": "CY", "domain": ".cy", "en_name": "Cyprus", "fa_name": "قبرس" },
    { "fips": "KG", "iso": "KG", "domain": ".kg", "en_name": "Kyrgyzstan", "fa_name": "قرقیزستان" },
    { "fips": "KZ", "iso": "KZ", "domain": ".kz", "en_name": "Kazakhstan", "fa_name": "قزاقستان" },
    { "fips": "AY", "iso": "AQ", "domain": ".aq", "en_name": "Antarctica", "fa_name": "قطب جنوب" },
    { "fips": "QA", "iso": "QA", "domain": ".qa", "en_name": "Qatar", "fa_name": "قطر" },
    { "fips": "IO", "iso": "IO", "domain": ".io", "en_name": "British Indian Ocean Territory", "fa_name": "قلمرو اقیانوس هند بریتانیا" },
    { "fips": "LA", "iso": "LA", "domain": ".la", "en_name": "Laos", "fa_name": "لائوس" },
    { "fips": "LE", "iso": "LB", "domain": ".lb", "en_name": "Lebanon", "fa_name": "لبنان" },
    { "fips": "LG", "iso": "LV", "domain": ".lv", "en_name": "Latvia", "fa_name": "لتونی" },
    { "fips": "LT", "iso": "LS", "domain": ".ls", "en_name": "Lesotho", "fa_name": "لسوتو" },
    { "fips": "PL", "iso": "PL", "domain": ".pl", "en_name": "Poland", "fa_name": "لهستان" },
    { "fips": "LU", "iso": "LU", "domain": ".lu", "en_name": "Luxembourg", "fa_name": "لوکزامبورگ" },
    { "fips": "LI", "iso": "LR", "domain": ".lr", "en_name": "Liberia", "fa_name": "لیبریا" },
    { "fips": "LH", "iso": "LT", "domain": ".lt", "en_name": "Lithuania", "fa_name": "لیتوانی" },
    { "fips": "LS", "iso": "LI", "domain": ".li", "en_name": "Liechtenstein", "fa_name": "لیختن اشتاین" },
    { "fips": "MA", "iso": "MG", "domain": ".mg", "en_name": "Madagascar", "fa_name": "ماداگاسکار" },
    { "fips": "MB", "iso": "MQ", "domain": ".mq", "en_name": "Martinique", "fa_name": "مارتینیک" },
    { "fips": "MI", "iso": "MW", "domain": ".mw", "en_name": "Malawi", "fa_name": "مالاوی" },
    { "fips": "MT", "iso": "MT", "domain": ".mt", "en_name": "Malta", "fa_name": "مالت" },
    { "fips": "MV", "iso": "MV", "domain": ".mv", "en_name": "Maldives", "fa_name": "مالدیو" },
    { "fips": "ML", "iso": "ML", "domain": ".ml", "en_name": "Mali", "fa_name": "مالی" },
    { "fips": "MY", "iso": "MY", "domain": ".my", "en_name": "Malaysia", "fa_name": "مالزی" },
    { "fips": "MC", "iso": "MO", "domain": ".mo", "en_name": "Macau", "fa_name": "ماکائو" },
    { "fips": "MF", "iso": "YT", "domain": ".yt", "en_name": "Mayotte", "fa_name": "مایوت" },
    { "fips": "HU", "iso": "HU", "domain": ".hu", "en_name": "Hungary", "fa_name": "مجارستان" },
    { "fips": "MO", "iso": "MA", "domain": ".ma", "en_name": "Morocco", "fa_name": "مراکش" },
    { "fips": "EG", "iso": "EG", "domain": ".eg", "en_name": "Egypt", "fa_name": "مصر" },
    { "fips": "MG", "iso": "MN", "domain": ".mn", "en_name": "Mongolia", "fa_name": "مغولستان" },
    { "fips": "VT", "iso": "VA", "domain": ".va", "en_name": "Holy See (Vatican City)", "fa_name": "مقدس (واتیکان)" },
    { "fips": "DX", "iso": "-", "domain": "-", "en_name": "Dhekelia Sovereign Base Area", "fa_name": "منطقه نظامی داکیلیا" },
    { "fips": "MR", "iso": "MR", "domain": ".mr", "en_name": "Mauritania", "fa_name": "موریتانی" },
    { "fips": "MP", "iso": "MU", "domain": ".mu", "en_name": "Mauritius", "fa_name": "موریس" },
    { "fips": "MZ", "iso": "MZ", "domain": ".mz", "en_name": "Mozambique", "fa_name": "موزامبیک" },
    { "fips": "MD", "iso": "MD", "domain": ".md", "en_name": "Moldova, Republic of", "fa_name": "مولداوی، جمهوری" },
    { "fips": "MN", "iso": "MC", "domain": ".mc", "en_name": "Monaco", "fa_name": "موناکو" },
    { "fips": "MH", "iso": "MS", "domain": ".ms", "en_name": "Montserrat", "fa_name": "مونتسرات" },
    { "fips": "MJ", "iso": "ME", "domain": ".me", "en_name": "Montenegro", "fa_name": "مونته نگرو" },
    { "fips": "MX", "iso": "MX", "domain": ".mx", "en_name": "Mexico", "fa_name": "مکزیک" },
    { "fips": "BM", "iso": "MM", "domain": ".mm", "en_name": "Myanmar", "fa_name": "میانمار" },
    { "fips": "FM", "iso": "FM", "domain": ".fm", "en_name": "Micronesia, Federated States of", "fa_name": "میکرونزی، ایالات فدرال" },
    { "fips": "NR", "iso": "NR", "domain": ".nr", "en_name": "Nauru", "fa_name": "نائورو" },
    { "fips": "WA", "iso": "NA", "domain": ".na", "en_name": "Namibia", "fa_name": "نامیبیا" },
    { "fips": "NO", "iso": "NO", "domain": ".no", "en_name": "Norway", "fa_name": "نروژ" },
    { "fips": "NP", "iso": "NP", "domain": ".np", "en_name": "Nepal", "fa_name": "نپال" },
    { "fips": "NG", "iso": "NE", "domain": ".ne", "en_name": "Niger", "fa_name": "نیجر" },
    { "fips": "NI", "iso": "NG", "domain": ".ng", "en_name": "Nigeria", "fa_name": "نیجریه" },
    { "fips": "NE", "iso": "NU", "domain": ".nu", "en_name": "Niue", "fa_name": "نیو" },
    { "fips": "NZ", "iso": "NZ", "domain": ".nz", "en_name": "New Zealand", "fa_name": "نیوزلند" },
    { "fips": "NU", "iso": "NI", "domain": ".ni", "en_name": "Nicaragua", "fa_name": "نیکاراگوئه" },
    { "fips": "HA", "iso": "HT", "domain": ".ht", "en_name": "Haiti", "fa_name": "هائیتی" },
    { "fips": "NL", "iso": "NL", "domain": ".nl", "en_name": "Netherlands", "fa_name": "هلند" },
    { "fips": "HO", "iso": "HN", "domain": ".hn", "en_name": "Honduras", "fa_name": "هندوراس" },
    { "fips": "IN", "iso": "IN", "domain": ".in", "en_name": "India", "fa_name": "هند" },
    { "fips": "HK", "iso": "HK", "domain": ".hk", "en_name": "Hong Kong", "fa_name": "هنگ کنگ" },
    { "fips": "NM", "iso": "", "domain": "", "en_name": "No Man's Land", "fa_name": "منطقه بی‌طرف" },
    { "fips": "WF", "iso": "WF", "domain": ".wf", "en_name": "Wallis and Futuna", "fa_name": "والیس و فوتونا" },
    { "fips": "NH", "iso": "VU", "domain": ".vu", "en_name": "Vanuatu", "fa_name": "وانواتو" },
    { "fips": "VE", "iso": "VE", "domain": ".ve", "en_name": "Venezuela", "fa_name": "ونزوئلا" },
    { "fips": "VM", "iso": "VN", "domain": ".vn", "en_name": "Vietnam", "fa_name": "ویتنام" },
    { "fips": "PA", "iso": "PY", "domain": ".py", "en_name": "Paraguay", "fa_name": "پاراگوئه" },
    { "fips": "PS", "iso": "PW", "domain": ".pw", "en_name": "Palau", "fa_name": "پالائو" },
    { "fips": "LQ", "iso": "UM", "domain": "-", "en_name": "Palmyra Atoll", "fa_name": "پالمیرا اتل" },
    { "fips": "PM", "iso": "PA", "domain": ".pa", "en_name": "Panama", "fa_name": "پاناما" },
    { "fips": "PP", "iso": "PG", "domain": ".pg", "en_name": "Papua New Guinea", "fa_name": "پاپوآ گینه نو" },
    { "fips": "PK", "iso": "PK", "domain": ".pk", "en_name": "Pakistan", "fa_name": "پاکستان" },
    { "fips": "PE", "iso": "PE", "domain": ".pe", "en_name": "Peru", "fa_name": "پرو" },
    { "fips": "FP", "iso": "PF", "domain": ".pf", "en_name": "French Polynesia", "fa_name": "پلینزی فرانسه" },
    { "fips": "RQ", "iso": "PR", "domain": ".pr", "en_name": "Puerto Rico", "fa_name": "پورتوریکو" },
    { "fips": "CD", "iso": "TD", "domain": ".td", "en_name": "Chad", "fa_name": "چاد" },
    { "fips": "CH", "iso": "CN", "domain": ".cn", "en_name": "China", "fa_name": "چين" },
    { "fips": "JA", "iso": "JP", "domain": ".jp", "en_name": "Japan", "fa_name": "ژاپن" },
    { "fips": "CS", "iso": "CR", "domain": ".cr", "en_name": "Costa Rica", "fa_name": "کاستاریکا" },
    { "fips": "NC", "iso": "NC", "domain": ".nc", "en_name": "New Caledonia", "fa_name": "کالدونیای جدید" },
    { "fips": "CB", "iso": "KH", "domain": ".kh", "en_name": "Cambodia", "fa_name": "کامبوج" },
    { "fips": "CM", "iso": "CM", "domain": ".cm", "en_name": "Cameroon", "fa_name": "کامرون" },
    { "fips": "CA", "iso": "CA", "domain": ".ca", "en_name": "Canada", "fa_name": "کانادا" },
    { "fips": "KS", "iso": "KR", "domain": ".kr", "en_name": "Korea, South", "fa_name": "کره جنوبی" },
    { "fips": "KN", "iso": "KP", "domain": ".kp", "en_name": "Korea, North", "fa_name": "کره شمالی" },
    { "fips": "HR", "iso": "HR", "domain": ".hr", "en_name": "Croatia", "fa_name": "کرواسی" },
    { "fips": "PO", "iso": "PT", "domain": ".pt", "en_name": "Portugal", "fa_name": "کشور پرتغال" },
    { "fips": "CO", "iso": "CO", "domain": ".co", "en_name": "Colombia", "fa_name": "کلمبیا" },
    { "fips": "CF", "iso": "CG", "domain": ".cg", "en_name": "Congo, Republic of the", "fa_name": "کنگو، جمهوری" },
    { "fips": "CG", "iso": "CD", "domain": ".cd", "en_name": "Congo, Democratic Republic of the", "fa_name": "کنگو، جمهوری دموکراتیک" },
    { "fips": "KE", "iso": "KE", "domain": ".ke", "en_name": "Kenya", "fa_name": "کنیا" },
    { "fips": "CU", "iso": "CU", "domain": ".cu", "en_name": "Cuba", "fa_name": "کوبا" },
    { "fips": "KV", "iso": "KV", "domain": "-", "en_name": "Kosovo", "fa_name": "کوزوو" },
    { "fips": "CN", "iso": "KM", "domain": ".km", "en_name": "Comoros", "fa_name": "کومور" },
    { "fips": "KU", "iso": "KW", "domain": ".kw", "en_name": "Kuwait", "fa_name": "کویت" },
    { "fips": "KR", "iso": "KI", "domain": ".ki", "en_name": "Kiribati", "fa_name": "کیریباتی" },
    { "fips": "KQ", "iso": "UM", "domain": "-", "en_name": "Kingman Reef", "fa_name": "کینگمن ریف" },
    { "fips": "CV", "iso": "CV", "domain": ".cv", "en_name": "Cape Verde", "fa_name": "کیپ ورد" },
    { "fips": "GB", "iso": "GA", "domain": ".ga", "en_name": "Gabon", "fa_name": "گابن" },
    { "fips": "GA", "iso": "GM", "domain": ".gm", "en_name": "Gambia, The", "fa_name": "گامبیا" },
    { "fips": "GY", "iso": "GY", "domain": ".gy", "en_name": "Guyana", "fa_name": "گایانا" },
    { "fips": "GJ", "iso": "GD", "domain": ".gd", "en_name": "Grenada", "fa_name": "گرانادا" },
    { "fips": "GL", "iso": "GL", "domain": ".gl", "en_name": "Greenland", "fa_name": "گرینلند" },
    { "fips": "GT", "iso": "GT", "domain": ".gt", "en_name": "Guatemala", "fa_name": "گواتمالا" },
    { "fips": "GP", "iso": "GP", "domain": ".gp", "en_name": "Guadeloupe", "fa_name": "گوادلوپ" },
    { "fips": "GQ", "iso": "GU", "domain": ".gu", "en_name": "Guam", "fa_name": "گوام" },
    { "fips": "GK", "iso": "-", "domain": ".gg", "en_name": "Guernsey", "fa_name": "گورنسی" },
    { "fips": "FG", "iso": "GF", "domain": ".gf", "en_name": "French Guiana", "fa_name": "گویان فرانسه" },
    { "fips": "GV", "iso": "GN", "domain": ".gn", "en_name": "Guinea", "fa_name": "گینه" },
    { "fips": "EK", "iso": "GQ", "domain": ".gq", "en_name": "Equatorial Guinea", "fa_name": "گینه استوایی" },
    { "fips": "PU", "iso": "GW", "domain": ".gw", "en_name": "Guinea-Bissau", "fa_name": "گینه بیسائو" },
    { "fips": "JN", "iso": "SJ", "domain": "-", "en_name": "یان ماین", "fa_name": "یان ماین" },
    { "fips": "YM", "iso": "YE", "domain": ".ye", "en_name": "Yemen", "fa_name": "یمن" },
    { "fips": "GR", "iso": "GR", "domain": ".gr", "en_name": "Greece", "fa_name": "یونان" }
]