name: Docker Image CI

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/build-push-action@v3.0.0
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/ternobo/ternobo-connect:0.1-$(date +%s)
